dist: trusty
addons:
  apt:
    packages:
      - chromium-chromedriver
  chrome: stable
language: node_js
node_js:
  - "8"
before_script:
  - "ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start